export const LOAD_USER_DETAILS = "LOAD_USER_DETAILS";
export const LOAD_USER_DETAILS_SUCCESS = "LOAD_USER_DETAILS_SUCCESS";
export const LOAD_USER_DETAILS_ERROR = "LOAD_USER_DETAILS_ERROR";

export const LOGOUT_INIT = "LOGOUT_INIT";
export const LOGOUT = "LOGOUT";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";